#!/bin/bash

dirs=$1
report=$1"_test_report.txt"
expect_suffix="_expect_output.txt"
actual_suffix="_actual_output.txt"

./Sample_output_parser $dirs
./Recursive_test $dirs

if [ -s "$report" ] 
then 
   rm $report
fi 

comparison=$(diff "Test_output/$dirs$expect_suffix" "Test_output/$dirs$actual_suffix")
if [ -n "$comparison" ] 
then 
  touch "$report"
  echo "$comparison" &>> $report
  echo "Something might be wrong. Investigate the $report file."
else 
  echo "Test passed."
fi
